name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  publish-ui-components-cafra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@cafradigital'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: 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